/* ============================================================
   Sample Data Seeding – Representative Examples
============================================================ */

-- Example 1: Small lookup table seeded via direct INSERT
-- (Other lookup tables follow the same pattern)
INSERT INTO dbo.EmpOffice (OfficeName) VALUES
    ('Vancouver'),
    ('Calgary'),
    ('Frankfurt');
GO

-- Example 2: Reference data seeded via multi-row INSERT
-- (Used where data volume is moderate)
INSERT INTO dbo.CompProcessor
    (CompProcNumber, CompProcName, CompProcSpeedGHz)
VALUES
    ('i5-10500', 'Intel Core i5-10500', 3.10),
    ('i7-1185G7','Intel Core i7-1185G7',3.00),
    ('M1Pro','Apple M1 Pro',3.20);
GO

-- Example 3: BULK INSERT with explicit primary keys
BULK INSERT dbo.Software
FROM 'D:\SqlSeedData\Software.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    TABLOCK
);
GO

-- Example 4: BULK INSERT with IDENTITY column generated by SQL Server
-- Primary key column omitted in CSV
BULK INSERT dbo.Employee
FROM 'D:\SqlSeedData\Employee.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    TABLOCK
);
GO
